{% set name = "mendeleev" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8817d2a62d377eaac13b561569206f7f8cf70b0807a633a4b104e5712f794246

build:
  number: 1
  entry_points:
    - element.py = mendeleev.cli:clielement
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
    - pyfiglet
    - colorama
    - sqlalchemy
    - pandas
    - numpy
  run:
    - python
    - numpy
    - pandas
    - sqlalchemy
    - pyfiglet
    - colorama

test:
  imports:
    - mendeleev
  commands:
    - element.py --help

about:
  home: https://bitbucket.org/lukaszmentel/mendeleev
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'A perdioc table of elements API and a database of atomic properties.'

  description: |
    This package provides an API for accessing various properties 
    of elements from the periodic table of elements.
  doc_url: http://mendeleev.readthedocs.org
  dev_url: https://bitbucket.org/lukaszmentel/mendeleev

extra:
  recipe-maintainers:
    - jan-janssen
    - lmmentel
